# Generated by Django 5.1.5 on 2025-02-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0002_event_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
