# Generated by Django 5.1.5 on 2025-02-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vibes.club'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vibes.student'),
        ),
    ]
