# Generated by Django 5.1.5 on 2025-03-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0007_remove_studentregistration_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibes.club'),
        ),
    ]
