# Generated by Django 5.1.5 on 2025-03-02 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0008_alter_event_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
