# Generated by Django 5.1.6 on 2025-03-20 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0009_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibes.event')),
                ('recipients', models.ManyToManyField(related_name='notifications', to='vibes.student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibes.club')),
            ],
        ),
    ]
