# Generated by Django 5.1.6 on 2025-04-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0011_event_is_group_event_event_max_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
