# Generated by Django 5.1.6 on 2025-04-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0012_event_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='utr',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
