# Generated by Django 5.1.6 on 2025-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0013_alter_studentregistration_utr'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
