# Generated by Django 5.1.6 on 2025-04-13 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0014_studentregistration_attended'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('runner_up_group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='vibes.event')),
                ('runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner_up_results', to='vibes.studentregistration')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_results', to='vibes.studentregistration')),
            ],
        ),
    ]
