# Generated by Django 5.1.6 on 2025-04-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0017_student_notification_studentregistration_eventresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventResult',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
    ]
