# Generated by Django 5.1.6 on 2025-04-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0018_remove_notification_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibes.event')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibes.club')),
                ('recipients', models.ManyToManyField(related_name='notifications', to='vibes.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('utr', models.CharField(blank=True, max_length=12, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_time', models.TimeField(blank=True, null=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibes.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibes.student')),
            ],
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('runner_up_group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='vibes.event')),
                ('runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner_up_results', to='vibes.studentregistration')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_results', to='vibes.studentregistration')),
            ],
        ),
    ]
